# Generated by Django 3.0.2 on 2020-02-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
